In [1]:
!pip install word2number

Defaulting to user installation because normal site-packages is not writeable


In [14]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from word2number import w2n

In [15]:
df = pd.read_csv('hiring.csv')
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [16]:
print(w2n.word_to_num("two"))

2


In [17]:
df['experience'] = df['experience'].apply(lambda x: w2n.word_to_num(x) if pd.notnull(x) else x)
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000

In [18]:
df.isnull().sum()

experience                    2
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [19]:
sime = SimpleImputer(strategy = "median")
simean = SimpleImputer(strategy = "mean")
df[["experience"]] = simean.fit_transform(df[["experience"]])
df[["test_score(out of 10)"]] = sime.fit_transform(df[["test_score(out of 10)"]])
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0    6.333333                    8.0                           9      50000
1    6.333333                    8.0                           6      45000
2    5.000000                    6.0                           7      60000
3    2.000000                   10.0                          10      65000
4    7.000000                    9.0                           6      70000

In [20]:
y = df.iloc[:, -1]
y.head()

0    50000
1    45000
2    60000
3    65000
4    70000
Name: salary($), dtype: int64

In [21]:
X = df.drop(columns = "salary($)", axis = 1)
X.head()

experience  test_score(out of 10)  interview_score(out of 10)
0    6.333333                    8.0                           9
1    6.333333                    8.0                           6
2    5.000000                    6.0                           7
3    2.000000                   10.0                          10
4    7.000000                    9.0                           6

In [22]:
reg = LinearRegression()
reg.fit(X, y)

LinearRegression()

In [23]:
reg.intercept_

14825.26549525492

In [24]:
reg.coef_

array([2624.77417774, 1220.70138265, 2785.79572368])

In [25]:
reg.predict([[2, 9, 6]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([47775.90063671])

In [26]:
reg.predict([[12, 10, 10]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([86387.52669148])